# Generated by Django 2.2.6 on 2019-10-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='socre',
            field=models.FloatField(default=0),
        ),
    ]
