# Generated by Django 2.2.6 on 2019-10-27 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sentence_socre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='socre',
            new_name='score',
        ),
    ]
