# Generated by Django 2.2.6 on 2019-10-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191027_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
