# Generated by Django 2.2.6 on 2019-10-26 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='content',
            new_name='text',
        ),
    ]
